config/routes.rb
Rails.application.routes.draw do
  root 'imei#show'
  post 'check', to: 'imei#check'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/imei_controller.rb
class ImeiController < ApplicationController
  protect_from_forgery with: :null_session

  def show
  end

  def check
    status = CoverageCheckService.check(params[:imei])
    render json: status
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/imei/show.html.slim
br
br

.row
  .col.l6.offset-l3.m8.offset-m2.s12
    .card-panel.grey.lighten-5.z-depth-1
      .row.center
        h5 Repairs and Services Coverage
      = form_tag check_path, remote: true, class: 'imei-form'
        .row
          .input-field.col.s12
            i.mdi-hardware-smartphone.prefix
            input#imei.validate type='text' name='imei'
            label for='imei' Enter IMEI
        .row.center
          button.btn.waves-effect.waves-light type='submit' CHECK
      #progress.progress
        .indeterminate
      #response
        br
        .row.center
          h5 Status
        #status-expired.card-panel.valign-wrapper
          i.mdi-alert-error.red-text.small
          | &nbsp;
          span Expired
        #status-active.card-panel.valign-wrapper
          i.mdi-action-verified-user.green-text.small
          | &nbsp;
          span Active
      #error
        br
        .card-panel.valign-wrapper.red.white-text
          i.mdi-alert-error.small
          | &nbsp;
          span Processing error


br

- content_for :footer
  ' IMEI examples: 013977000323877, 013896000639712. You can check them on
  a.blue-text.text-lighten-3 href='https://selfsolve.apple.com/agreementWarrantyDynamic.do'
   | Apple Support

app/views/layouts/application.html.slim
doctype html
html
  head
    title Scrape Demo
    meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav role='navigation'
      .nav-wrapper.container
        = link_to 'Scrape Demo', root_path, class: 'brand-logo'

    main.container
      br
      == yield

    footer.page-footer
      .container
        p.blue-text.text-lighten-4
          == yield :footer
      .footer-copyright
        .container
          ' Made by
          a.blue-text.text-lighten-4 href='https://github.com/szyablitsky'
            | Sergey Zyablitsky